pipeline {
    agent{
	docker	{
	image 'maven:3.9.8-sapmachine-21'
	args '-v $HOME/.m2:/root/.m2'
		}
	}
    
// cuando hay cambios
    stages{
        stage("build"){
        	when{
        		changeset "**/result/**"
        	}
            steps{
            	echo 'Building app'
            	dir('result'){
            		sh 'npm install'
            	}
            }
        }
        stage("test"){
                when{
        		changeset "**/result/**"
        	}
            steps{
                 echo 'Testing app'
                 dir('result'){
                 	sh 'npm i'
                 	sh 'npm test'
                 }
            }
        }
    }       
    post{         

        always{      

             echo 'This pipeline is completed.'
             slackSend (channel: "#result-commits", message: "Pipeline execution complete: ${env.JOB_NAME} ${env.BUILD_NUMBER}")
        }
    }
}
