pipeline {
    agent any          

    stages{
        stage("one"){
            steps{
                 echo 'steps, eurosteps 1'
            }
        }
        stage("two"){
            steps{
                 echo 'step 2'
            }
        }
        stage("three"){
            steps{
                 echo 'step 3'
            }
        }
    }       
    post{         

        always{      

             echo 'This pipeline is completed.'
        }
    }
}
